# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PROBE_cpp0_5_6 <- function(y, Z, Wt, W_var, delta, beta_vec, Z2, sigma2) {
    .Call(`_probe_PROBE_cpp0_5_6`, y, Z, Wt, W_var, delta, beta_vec, Z2, sigma2)
}

PROBE_cpp0_5_6_covs <- function(y, Z, Wt, W_var, delta, beta_vec, Z2, sigma2, X) {
    .Call(`_probe_PROBE_cpp0_5_6_covs`, y, Z, Wt, W_var, delta, beta_vec, Z2, sigma2, X)
}

PROBE_one_cpp <- function(y, Z, Wt, W_var, delta, beta_vec, Z2, sigma2, update_order) {
    .Call(`_probe_PROBE_one_cpp`, y, Z, Wt, W_var, delta, beta_vec, Z2, sigma2, update_order)
}

LM_by_col <- function(y, X, sigma2) {
    .Call(`_probe_LM_by_col`, y, X, sigma2)
}

LM_w_COVS_by_col <- function(y, X, COVS, sigma2) {
    .Call(`_probe_LM_w_COVS_by_col`, y, X, COVS, sigma2)
}

MVM <- function(X, v) {
    .Call(`_probe_MVM`, X, v)
}

Row_sum <- function(X) {
    .Call(`_probe_Row_sum`, X)
}

